### ISSUE TITLE
InitializedParams are not mentioned in the LSP

### ISSUE THREAD

**Issue by Trolldemorted** [eclipse/lsp4j#102]
aee5a6b410b8e63ce2de4f84ff1e7b7542a40907 introduced `InitializedParams` and deprecated `initialized()`.

I cannot find a reference on `InitializedParams` in the protocol, and `initialized(InitializedParams params)` ist just calling `initialized()` despite it being deprecated.

Is this intentional?

**Comment by akosyakov** [comment]
It will be added in LSP 4.0, but we need it now to be compatible with `vscode-jsonrpc`: https://github.com/Microsoft/vscode-languageserver-node/blob/e65f6fcdfa5467599b78d0ed25c2871be4530457/client/src/protocol.ts#L749

Otherwise, your log will be full of warning of an unexpected param, since VS code already sends it.

**Comment by Trolldemorted** [comment]
Sorry, i didn't know that!

So they implement first and specify their protocol later?
