### ISSUE TITLE
JSON RPC specification violation on ID field.

### ISSUE THREAD

**Issue by hemikak** [eclipse/lsp4j#138]
Hi,

According to the JSON RPC 2.0 specification, the "id" field `It MUST be the same as the value of the id member in the Request Object.`. But if the request message send the 'id' value as an integer, it will get changed to a string[1] in the response.

[1] -
 https://github.com/eclipse/lsp4j/blob/master/org.eclipse.lsp4j.jsonrpc/src/main/java/org/eclipse/lsp4j/jsonrpc/messages/ResponseMessage.java#L25

Regards,
Hemika

**Comment by jonahkichwacoders** [comment]
Interesting, as my implementation of the JSON RPC 2.0-like Debug Protocol uses integers (see #130) for the ID it would be convenient if the id object was simply `Object`, or perhaps `Either<Object,Integer>` because at the moment my `DebugMessageTypeAdapter` is converting integers back and forth to strings all the time.

**Comment by hemikak** [comment]
@jonahkichwacoders 

Yes, "id" can be an integer too.

As per the specification it states that "id" field `MUST contain a String, Number, or NULL value if included`. 

We can have it as an Object field and do validation upon setting the value. The same goes to the RequestMessage class (https://github.com/eclipse/lsp4j/blob/master/org.eclipse.lsp4j.jsonrpc/src/main/java/org/eclipse/lsp4j/jsonrpc/messages/RequestMessage.java#L25)
