### ISSUE TITLE
Support for SnippetText and CompletionItem.range

### ISSUE THREAD

**Issue by gorkem** [eclipse/lsp4j#15]
LSP is moving to a more defined syntax for defining tab stops and the old way is deprecating. JDT language server is [asked](https://github.com/redhat-developer/vscode-java/issues/99) to adopt to the new syntax. 

See also https://github.com/Microsoft/language-server-protocol/issues/82 and https://github.com/Microsoft/language-server-protocol/issues/75

**Comment by svenefftinge** [comment]
Thanks for the pointer. These union types in the protocol are hard to map.

**Comment by svenefftinge** [comment]
We will introduce an `Either` type to model union types.

**Comment by svenefftinge** [comment]
So this turns out to be not s o simple, because in order to check whether some json conforms to left or to right the simple lookahead of one provided by TypeAdapters in gson is insufficient. Since Gson is entirely based on readers and it would be very hacky to try to copy the reader state to do full back tracking, I believe this is not the way to go.

I see two options:
1) We go with java.lang.Object (resp. gson's JsonObject) for union typed properties.
This would be a very simple solution, but would basically remove all type checking for the whole sub tree of any union-typed property.

2) We change the data structures such that they don't copy the json data into POJOs but generate data structures that wrap the JsonObject instances and only provide statically typed getters and setters to work with the properties. This is more complicated because we will need to cover lists and string indexed maps, too. However, the advantages of this approach would be
* no more conversion, as the JsonObject just get wrapped
* easy extension, since you could access the wrapped JsonObect and ask for undefined properties
* union type mapping would work

downsides: 
* possible object identity surprises. E.g. asking a getter to nested object twice would return two different Java objects (they are equal though).

Attach files by dragging & dropping,  Choose Files selecting them, or pasting from the clipboard.

**Comment by svenefftinge** [comment]
The wrapping approach seems too complicated, so I prefer to go with option 1).
I pushed my work on the wrapping to a separate branch in case we want to reconsider it in future.

**Comment by akosyakov** [comment]
Resolved with https://github.com/eclipse/lsp4j/issues/60
