### ISSUE TITLE
InvocationTargetException on code completion

### ISSUE THREAD

**Issue by amiramw** [eclipse/lsp4j#171]
I'm getting an InvocationTargetException with jdt_ls-0.12.1 when trying to complete `system.ou` on the following class:
```
public class test1 {

public static void main(String [] args)
{
  System.ou
}

}
```
It happened to me once and now doesn't reproduce...

Could you make something of it?

![image](https://user-images.githubusercontent.com/9420921/37714652-bf643658-2d22-11e8-8057-e730e2693917.png)

**Comment by spoenemann** [comment]
Which LSP4J version does it use?

**Comment by amiramw** [comment]
Seems 0.3.0.
Jars are:
org.eclipse.lsp4j.jsonrpc_0.3.0.v20170913-0639
org.eclipse.lsp4j_0.3.0.v20170913-0639

**Comment by spoenemann** [comment]
InvocationTargetException indicates that the cause of the exception is in the local service implementation, which in this case is provided by jdt_ls. You should be able to see this if you look further below in the stack trace.

Please reopen if the problem occurs again and it turns out that my assumption is wrong.
