### ISSUE TITLE
Add option to Skip Headers in StreamMessage(Producer/Consumer)

### ISSUE THREAD

**Issue by cdietrich** [eclipse/lsp4j#189]
It would be nice to have an option to skip Headers in StreamMessage(Producer/Consumer) to be able to directly talk to a client using https://github.com/TypeFox/vscode-ws-jsonrpc (e.g. https://github.com/TypeFox/monaco-languageclient)

in the current state this wont work cause the client does not produce/expect the headers sent via the protocol

see https://github.com/TypeFox/vscode-ws-jsonrpc/issues/6

**Comment by tocjent** [comment]
Same here, currently we are using a workaround and adding the headers manually, but it's far from ideal.

**Comment by spoenemann** [comment]
Skipping headers in StreamMessageProducer / StreamMessageConsumer doesn't make any sense because then you don't know when a message ends in the byte stream. For your use case, you would need specialized implementations of MessageProducer / MessageConsumer that handle messages as individual Strings instead of reading / writing byte streams. The current Launcher API doesn't support that, but you're free to wire up such a thing yourself, just have a look at the code of Launcher.Builder.

**Comment by cdietrich** [comment]
yes. but basically everyone who uses websockets has to do that. so why to do it 100 times if it can be done once

**Comment by jonahgraham** [comment]
See PR #211 - it is @juliandolby starting point of websocket support for LSP4J.

**Comment by spoenemann** [comment]
While implementing #314 I realized that there's no use in such an option to skip headers, since that reduces the message consumer / producer to simply invoking the MessageJsonHandler.
