### ISSUE TITLE
Review using null for fields with no values

### ISSUE THREAD

**Issue by jonahgraham** [eclipse/lsp4j#240]
Follow up to #239. @drungrin in #238 fixed the `"argument"` part of [this](https://github.com/eclipse/lsp4j/issues/239#issuecomment-415422626), the rest needs a closer review:

> I think the correct place to make this change is in DebugMessageTypeAdapter's write method to omit the "arguments" if the getParams returns null. I suspect the same thing may apply to "body" of notifications and responses and "message" of error responses, all of those within the same write method.

**Comment by drungrin** [comment]
The body is omitted on responses in Visual Studio Code. On notifications threre is always a body, since the only notification without argument is "initialized", which is sent by the Java Debug Server with a body. I believe it is safe to omit the body in the notifications also.

`"{"event":"initialized","body":{"type":"initialized"},"seq":2,"type":"event"}"`

`"{"success":true,"request_seq":2,"command":"launch","seq":3,"type":"response"}"`

**Comment by jonahgraham** [comment]
I don't think this issue needs to hold up the 0.5.0 release, updating milestone to 0.6.0.

**Comment by jonahgraham** [comment]
@drungrin Thanks for following up.
