### ISSUE TITLE
Don't use version range when declaring dependencies

### ISSUE THREAD

**Issue by fbricon** [eclipse/lsp4j#276]
lsp4xml is currently depending on lsp4j 0.5.0.M1, which uses a version range to declare its dependency towards org.eclipse.xtend.lib:

```xml
    <dependency>
      <groupId>org.eclipse.xtend</groupId>
      <artifactId>org.eclipse.xtend.lib</artifactId>
      <version>[2.11.0,3)</version>
      <scope>compile</scope>
    </dependency>
```

The Travis build [failed](https://travis-ci.org/angelozerr/lsp4xml/builds/443186891) because Travis automatically adds some snapshot repositories to its settings, and Maven then tries (and fails) to pick up a snapshot of org.eclipse.xtend.lib. 
```
[ERROR] Failed to execute goal on project org.eclipse.lsp4xml: Could not resolve dependencies for project org.eclipse:org.eclipse.lsp4xml:jar:0.0.2-SNAPSHOT: Could not find artifact org.eclipse.xtext:org.eclipse.xtext.xbase.lib:jar:2.16.0-20181005.015814-31 in sonatype-snapshots (https://oss.sonatype.org/content/repositories/snapshots/) -> [Help 1]
```

Locking down the version fixes the issue.

Using version ranges in a build is bad. Like crossing-the-streams bad (look at the NPM mess before they added lock files). You can not guarantee build idempotency so please don't do it.

**Comment by spoenemann** [comment]
You can configure the actual version to use in your own build. The range of versions is there because we expect them all to work with LSP4J. Fixing a specific version here would cause conflicts when a downstream project has another dependency with a different version. Then you would need to resolve that conflict in your own build, too, but would have no hint on whether the libs will work together.

Lock files are actually a very good solution to make builds repeatable. We should have them in Java, too.
