### ISSUE TITLE
Is there a "Hello world" about how to finish a language server with LSP4J?

### ISSUE THREAD

**Issue by Nicholas-zhao4** [eclipse/lsp4j#372]
It is a little hard for me to implement the server without a guideline.  
![image](https://user-images.githubusercontent.com/54941417/66247975-f29a2180-e753-11e9-8011-6d0d8e30d83a.png)

I implemented the server and client interface, but I do not know the meaning of the functions belongs to the interface with no comments.  
![image](https://user-images.githubusercontent.com/54941417/66247971-e31ad880-e753-11e9-919e-c5101844775a.png)
So，I want to ask a specification or introduction for the meaning of these functions belong to the interface `LanguageServer` and `LanguageClient` and how to use them.
Or some other documents that can help me understand how to use the interface `LanguageServer` and `LanguageClient`  deeply.  Such as the meaning of the parameters and the return , what I should do to implement the functions.
Really Thanks.

**Comment by spoenemann** [comment]
@Nicholas-zhao4 the protocol methods, parameters and return values are documented here:

https://microsoft.github.io/language-server-protocol/

**Comment by angelozerr** [comment]
vscode provides this LSP sample https://github.com/microsoft/vscode-extension-samples/tree/master/lsp-sample (client and server side)

I think it could be good that LSP4J provides this same sample implemented with LSP4J (on server side only I think because developping a LSP4J client is not required to integrate it in Java Editor like Eclipse IDE)

**Comment by robstryker** [comment]
I would argue this issue can be closed and has been answered
