### ISSUE TITLE
Update site does not repackage guava

### ISSUE THREAD

**Issue by cdietrich** [eclipse/lsp4j#374]
Update site does not repackage guava. this prevents us from fixing the mwe update site
https://github.com/eclipse/mwe/issues/89
see also https://github.com/eclipse/lsp4j/issues/359

**Comment by jonahgraham** [comment]
@cdietrich  as a result of this change the p2 repo now contains com.google.guava 21.0.0 instead of (presumably intended) 27.0.0 based on the changes to .target file:

Compare p2 repo before and after:

before: http://services.typefox.io/open-source/jenkins/job/lsp4j/job/master/26/artifact/build/p2-repository/plugins/
after: http://services.typefox.io/open-source/jenkins/job/lsp4j/job/master/27/artifact/build/p2-repository/plugins/

Key part is after has in its plugins:
com.google.guava_21.0.0.jar and  com.google.guava.source_27.1.0.v20190517-1946.jar

**Comment by cdietrich** [comment]
Hmm but why ...

**Comment by cdietrich** [comment]
btw i also wonder why we dont package gson as well.

**Comment by jonahgraham** [comment]
I wasn't clear on the repacking expectations. I.e. Why are some deps included and others not. In addition, what about things like xbase? Should consumers be able to get everything for lsp4j repo, or have to hunt around? And if they have to hunt around anyway, why not leave orbit deps in the list? There are probably some decisions on this made long ago that I am not familiar with.

**Comment by cdietrich** [comment]
Me neither. But lsp4j currently causes this https://github.com/eclipse/mwe/issues/89

**Comment by cdietrich** [comment]
Xbase is part of simrel 
Orbit is just with the things projects package
