### ISSUE TITLE
Consider to provide drops again

### ISSUE THREAD

**Issue by cdietrich** [eclipse/lsp4j#381]
We should consider to provide drops again
https://download.eclipse.org/lsp4j/downloads/drops/?d
for users that easily want to download the update site e.g. when behind a proxy

found while reviewing https://github.com/eclipse/lsp4j/pull/378/files

**Comment by jonahgraham** [comment]
I set Milestone to 0.9.0 - but if no one is actually interested in drops I don't really want to do the extra work. @cdietrich do you need them?

**Comment by jonahgraham** [comment]
No one has indicated they need them, so closing for now. Please comment and reopen if you want them.

**Comment by cdietrich** [comment]
cc @iloveeclipse

**Comment by iloveeclipse** [comment]
Yep, we are interested.

**Comment by jonahgraham** [comment]
Thanks @iloveeclipse - as it is useful to you still I will manually add the 0.9.0 version and then add this step the scripted release for 0.10.0 and onwards.

**Comment by jonahgraham** [comment]
0.9.0's drop is there now: http://download.eclipse.org/lsp4j/updates/releases/0.9.0/v0.9.0.zip  and linked from https://github.com/eclipse/lsp4j/releases/tag/v0.9.0

Note I intend to put the zipped drop in the same release directory rather than having them split into different locations on download.eclipse.org. A copy of maven repo also exists in the same [release](https://download.eclipse.org/lsp4j/updates/releases/0.9.0/) directory (as [zip](http://download.eclipse.org/lsp4j/updates/releases/0.9.0/maven-repository.zip) and [unzipped](http://download.eclipse.org/lsp4j/updates/releases/0.9.0/maven-repository/)).

**Comment by jonahgraham** [comment]
PR #465 automates the inclusion of the zipped p2 repo.
