### ISSUE TITLE
LSP4J fails to parse TextDocumentSyncOptions with a boolean value for property `save`

### ISSUE THREAD

**Issue by planger** [eclipse/lsp4j#426]
The type `TextDocumentSyncOptions` is defined as follows in the LSP spec:

```typescript
export interface TextDocumentSyncOptions {
	...
	save?: boolean | SaveOptions;
}
```

However, LSP4J doesn't handle boolean values, only `SaveOptions`.

Note that this may stem from a slight inconsistency in the LSP spec, which got resolved only quite recently. See also https://github.com/microsoft/language-server-protocol/issues/989

**Comment by jonahgraham** [comment]
Thanks @planger for the report, getting it fixed in LSP spec and providing a PR. I, or someone else here, will have a review of it soon.

Can you let me know of your use case a little more? This will help us schedule a release that has this fix in it. For example, are you using this with LSP4E and need that release coordinated, or some other use cases. Thanks.

**Comment by planger** [comment]
Thanks @jonahgraham for the fast reply!

I came across this issue when prototyping a setup based on CDT.lsp + LSP4E + clangd-11. Since clangd-11 sends a boolean for `TextDocumentSyncOptions.save`, LSP4J failed parsing the LSP messages during the initialization, which lead me to the LSP spec inconsistency that caused clangd-11 and LSP4J/LSP4E getting incompatible with each other.

For my use case, it'd be great to have this coordinated with LSP4E so that I can set up an Eclipse installation that has the latest CDT.lsp + LSP4E + LSP4J (with the fix) on board. However, even though it would help a lot, there is no need to go through any hurdles for you with that. I guess, I should be able to patch my way around this issue for now in any case.

Thanks a lot in advance!
