### ISSUE TITLE
Add support for `client/executeCommand` request

### ISSUE THREAD

**Issue by kdvolder** [eclipse/lsp4j#468]
This is a protocol extension that I have proposed here: https://github.com/microsoft/language-server-protocol/issues/1117
It allows a server to request the client to execute a command. 

Also related: https://github.com/eclipse/wildwebdeveloper/pull/543

This adds some custom protocol to xml language server that does essentially the same thing. 

It was suggested that instead, if we could hasten the adoption/implementation of this (hopefully soon) to be standardized message into LSP4e and LSP4j, then that particular PR and its custom extension becomes obsolete, saving work all around.

That seems like a good solution to me if it can be done relatively quickly. I'm willing to create PR against LSP4J for this.

However the question (here https://github.com/eclipse/wildwebdeveloper/pull/543#issuecomment-723222353)  is whether you guys would be okay with doing this before the LSP extension is officially part of the protocol). @mickaelistria is okay with this for the lsp4e side, but can't speak for LSP4J.

**Comment by jonahgraham** [comment]
@kdvolder sorry you didn't get an answer to this earlier - and I can't provide one for you now (I am more on the DAP side, rather than the LSP side). I believe that in the past only official releases and pre-releases of the spec have made it into LSP4J. I believe that the whole idea of the extensibility that the protocol can be extended by the clients and if the protocol is approved then we can move it to LSP4J in line with the LSP spec release. Indeed it looks like this was done already (in WWD)?

I am closing this for now as I think I have answered your question (and perhaps pinged others to revisit the question).
