### ISSUE TITLE
enable writing null values with JSON in MessageJsonHandler 

### ISSUE THREAD

**Issue by jcompagner** [eclipse/lsp4j#470]
can the gson be created with an extra factory call ".serializeNulls()" around here:

https://github.com/eclipse/lsp4j/blob/master/org.eclipse.lsp4j.jsonrpc/src/main/java/org/eclipse/lsp4j/jsonrpc/json/MessageJsonHandler.java#L79

this is because null values are a valid value that i can't output now.

as an example nodePath in the eslintServer:

https://github.com/microsoft/vscode-eslint/blob/master/server/src/eslintServer.ts#L237

must be a string or null (so not undefined)
later one:

https://github.com/microsoft/vscode-eslint/blob/master/server/src/eslintServer.ts#L761

it actually test really for null, not null or undefined

So i can't give the exact configuration i want, because not giving it will will bomb out because it will enter the above if but then the next call to path.isAbsolute(nodePath) will bomb out because that doesn't expect the argument to be undefined

**Comment by jonahgraham** [comment]
Hi @jcompagner - I think the challenge here is that in Java we don't differentiate between `null` and `undefined` like javascript does. If we serialize `null`s, would that mean that every `null` field is then serialized as `null`? That would lead to other places in javascript expecting `undefined` to then be unreachabe? 

Based on my understanding of the problem (see below). Perhaps what is needed is a special case in LSP4J that you can annotate a field to say that it should be serialized even if it is null? I think a solution like this would be reasonable.

What does your Java types look like for vscode-eslint's CommonSetting at the moment?

----

Take the below with a grain of salt:

Looking at the history of eslint, a year ago `undefined` was legal for nodePath and then it became invalid in https://github.com/microsoft/vscode-eslint/commit/25f335567f9ab2fdd3cc62bf0611f831f2afa408 - the extension side of things handled this by [converting](https://github.com/microsoft/vscode-eslint/blob/51da58ba4354de194d120d4da28b211033615a79/client%2Fsrc%2Fextension.ts#L1445) `undefined` to `null` before passing it to the server. I assume the case we are dealing with here is that you are trying to reuse the server with a different frontend/extension implementation? If so, then the vscode-eslint folk presumably don't consider that interface API? It would be nice to just provide the one line fix to vscode-eslint so that undefined was allowed again - i.e. push the `undefined` -> `null` translation down a layer?

**Comment by jcompagner** [comment]
first yes i was debugging Wild Wide Developer

https://github.com/eclipse/wildwebdeveloper/blob/master/org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/eslint/ESLintClientImpl.java#L34

i need to give here a null to it because of the implementation the use in eslintServer

but how don't we differentiate in java between null and undefined
we have that concept for sure, at least in data packages (maps, what json is for us)

map.put("key", "value")
or
map.put("key", null)
or
map (put nothing) == undefined.

Are you saying that MesssageJsonHandler gets a lot of maps that it serializes with null values? (but keys are there?)
and we really expect that those should not be transfered over, why not follow exactly the json/js way?
if they key are there we output it, with the value or with : null
if they key is not here we don't output it of course and that is then the same as undefined

Now we are saying null in java is undefined in js. That i find a bit weird 

But i guess we just have to know then we depends on this behavior, but why put in a null value in a map in the first place then? (its completely useless now)

**Comment by jonahgraham** [comment]
I had a look at the code in wwd. The problem is if you turn on serializeNulls you get null *fields* and collection entries. I am pretty sure it is a non-starter to have all null fields be output.

Is this a case where a ResponseJsonAdapter is needed for configuration repsonse? See the gson bug on this issue that has a way to do this: https://github.com/google/gson/issues/913#issuecomment-335572100

I can't recall if the ResponseJsonAdapter can be added to the subclass directly or if LSP4J needs to change.

An alternative may be to have lsp4j always serialize nulls within collections, perhaps applying the pattern from https://github.com/google/gson/issues/913#issuecomment-335572100 to https://github.com/eclipse/lsp4j/blob/ad99a3d77139351dbc00c2dacd388fe749652309/org.eclipse.lsp4j.jsonrpc%2Fsrc%2Fmain%2Fjava%2Forg%2Feclipse%2Flsp4j%2Fjsonrpc%2Fjson%2Fadapters%2FCollectionTypeAdapter.java#L40 - however that pattern needs to know when it recurses into a non-collection object and turn off serialize nulls again.

**Comment by jonahgraham** [comment]
@jcompagner Is this still an active issue, or do you have a solution?

**Comment by jcompagner** [comment]
in the end i didn't really need it because i could solve it differently.
But if i would need to set that property, that is then a problem because it is just now way todo that.

**Comment by jonahgraham** [comment]
> But if i would need to set that property, that is then a problem because it is just no way todo that.

Sorry, I had been addressing the question of adding serializeNulls all the time to LSP4J itself. You can do it as a user of LSP4J numerous ways. For example:

- Option 1: Call Launcher.createIoLauncher with a Consumer<GsonBuilder> configureGson that adds the serializeNulls.
- Option 2: extend MessageJsonHandler (like DebugMessageJsonHandler) and override getDefaultGsonBuilder. 

Please let us know if thee is anything else that you need.
