### ISSUE TITLE
Have you deleted the wrong file recently？！

### ISSUE THREAD

**Issue by mozhuanzuojing** [eclipse/lsp4j#518]
# such as CompletionItem.java I can't find it

![image](https://user-images.githubusercontent.com/63572041/110225575-db033180-7f21-11eb-80b7-6edcad21dd25.png)

**Comment by jonahgraham** [comment]
Hi @mozhuanzuojing - no, that file was intentionally deleted. Indeed those java files should arguably never have been committed to source control as they are generated. See conversation starting at https://github.com/eclipse/lsp4j/issues/199#issuecomment-754918513 

Are you running into a problem that I can help with?

**Comment by mozhuanzuojing** [comment]
> Hi @mozhuanzuojing - no, that file was intentionally deleted. Indeed those java files should arguably never have been committed to source control as they are generated. See conversation starting at [#199 (comment)](https://github.com/eclipse/lsp4j/issues/199#issuecomment-754918513)
> 
> Are you running into a problem that I can help with?

I am compiling the project [eclipse.jdt.ls] using the latest lsp4j and found that the class is not found
E.g https://github.com/eclipse/eclipse.jdt.ls/blob/master/org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java
![image](https://user-images.githubusercontent.com/63572041/110226237-7f887200-7f28-11eb-82a3-ebc8f5318bb8.png)

**Comment by jonahgraham** [comment]
If you are having a problem setting up the JDT LS sources you should [be in touch](https://github.com/eclipse/eclipse.jdt.ls#feedback) with that project rather than here at LSP4J. They are more likely to be able to help.

However at a guess you have LSP4J checked out as source? Is so you need to follow steps in [LSP4J Eclipse setup](https://github.com/eclipse/lsp4j/blob/master/Contributing.md#eclipse) to make sure you have the LSP4J Java files generated from xtend files up to date.

Also, AFAICT eclipse.jdt.ls is currently [targeting LSP4J 0.9.0](https://github.com/eclipse/eclipse.jdt.ls/blob/babe6d36305b85ac877e883b6fd7a880ccd20417/org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target#L46) and is expecting to pull that in from the [pre-built files](https://github.com/eclipse/eclipse.jdt.ls#first-time-setup).

I am closing this here as there is no LSP4J issue as far as I understand. Please feel free to provide more details and we can reopen if there is an LSP4J issue.

Thanks!

**Comment by jonahgraham** [comment]
PS If it helps, CompletionItem class is defined here in the xtend file:

https://github.com/eclipse/lsp4j/blob/d6216cd86ffdac4bbb9d8773fee07d7b0f4c66be/org.eclipse.lsp4j/src/main/java/org/eclipse/lsp4j/Protocol.xtend#L2322

**Comment by mozhuanzuojing** [comment]
Tank you! it worked

**Comment by mozhuanzuojing** [comment]
Tank you! it worked
