### ISSUE TITLE
(JSON-RPC) Content-Length header on socket connection

### ISSUE THREAD

**Issue by gdaniel** [eclipse/lsp4j#607]
I followed [this tutorial](https://www.eclipse.org/community/eclipse_newsletter/2017/may/article2.php) to create a JSON-RPC client/server communicating through a socket. Then I built a Python client to access the server, but couldn't make it work because my client wasn't sending the `Content-Length` header before the JSON payload, and this header is required by [StreamMessageProducer](https://github.com/eclipse/lsp4j/blob/main/org.eclipse.lsp4j.jsonrpc/src/main/java/org/eclipse/lsp4j/jsonrpc/json/StreamMessageProducer.java#L91).

I guess this issue is very similar to #189, and I understand this header eases the parsing of the bytes stream, but I don't see any header in the JSON-RPC specification. It is part of the LSP specification though, so I am wondering if enforcing this header for every JSON-RPC server is a design decision, or if it crept from LSP to the generic JSON-RPC implementation.

**Comment by jonahgraham** [comment]
Hi @gdaniel - I think the issue here is that the json-rpc implementation here was done specifically for LSP (and later adapted for DAP). A fully generic json-rpc implementation was somewhat out of the [scope](https://projects.eclipse.org/projects/technology.lsp4j/governance) of the LSP4J project despite the comment at the end of that article by @akosyakov. 

That said, a clean PR (including tests) that that added such additional functionality would be welcome!
